[template]
src = "nginx.tmpl"
dest = "/etc/nginx/sites-available/autoconfig"
owner = "nginx"
mode = "0644"
keys = ["/nginx"]
reload_cmd  = "/etc/init.d/nginx restart"
check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
